controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["left_f_wheel_joint", "left_b_wheel_joint"]
      right_wheel_names: ["right_f_wheel_joint", "right_b_wheel_joint"]
      wheel_separation: 0.3
      wheel_radius: 0.05
      base_frame_id: base_link
      odom_frame_id: odom
      cmd_vel_timeout: 0.25
      use_stamped_vel: false
      publish_rate: 50.0
