controller_manager:
  ros__parameters:
    update_rate: 100
    controller_list:
      - name: diff_drive_controller
        type: diff_drive_controller/DiffDriveController
        parameters:
          left_wheel_names: ["left_wheel_joint"]
          right_wheel_names: ["right_wheel_joint"]
          publish_rate: 50
          wheel_separation: 0.95
          wheel_radius: 0.3
