controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_x_velocity: 0.1
      max_x_velocity: 0.5
      min_theta_velocity: 0.5
      max_theta_velocity: 1.0
      critics: ["RotateToGoal"]
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoalCritic"